import { useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTwoFactor } from '../hooks/useTwoFactor';
import meridianLogomark from '../../../assets/brand/meridian-logomark.svg';
import shieldCheckIcon from '../../../assets/icons/shield-check.svg';
import arrowLeftIcon from '../../../assets/icons/arrow-left.svg';

/**
 * SCR-006 — Two Factor Authentication Screen. Node 19:5127, Figma page "Page 1".
 *
 * Figma models only the default code-entry state (6-digit OTP split
 * into two groups of three, "Authenticator app" method badge, resend
 * countdown, "trust this device" checkbox). An inline error-banner
 * state was added beyond Figma per agent-rules.md §5's real-error
 * requirement — same extrapolation precedent as every other auth
 * screen in this feature (SCR-001 through SCR-005).
 *
 * "Use another method" has no corresponding screen in the Figma
 * inventory (only one verification-method badge — "Authenticator
 * app" — exists in the whole file) and MOD-002's spec does not define
 * alternate 2FA delivery channels. Per agent-rules.md §5's rule
 * against fabricating backend/navigation behavior that doesn't exist,
 * this link is rendered disabled with an explanatory title, mirroring
 * LoginScreen's disabled "Continue with SSO" precedent, rather than
 * routing to a screen that doesn't exist.
 *
 * MOCK BOUNDARY: `frontend/src/features/auth/twoFactorApi.js` attempts
 * real `POST /api/auth/2fa/verify` and `POST /api/auth/2fa/resend`
 * requests first, falling back to a mocked outcome only when the
 * endpoint is unreachable (no MOD-002 backend deployed yet) — mirrors
 * the rest of the auth feature's mock-fallback shape.
 */
export default function TwoFactorAuthenticationScreen() {
  const navigate = useNavigate();
  const {
    digits,
    setDigit,
    handleKeyDown,
    handlePaste,
    inputRefs,
    trustDevice,
    setTrustDevice,
    codeComplete,
    submitting,
    verifyError,
    resending,
    resendSent,
    resendError,
    cooldown,
    resend,
    submit,
  } = useTwoFactor();
  const errorBannerRef = useRef(null);

  // Mirrors EmailVerificationScreen's precedent of moving focus to the
  // error region on failure, rather than only to the (now emptied)
  // first OTP cell — so screen-reader users are told why before
  // landing back in a form field.
  useEffect(() => {
    if (verifyError) errorBannerRef.current?.focus();
  }, [verifyError]);

  async function handleSubmit(e) {
    e.preventDefault();
    const ok = await submit();
    if (ok) navigate('/dashboard', { replace: true });
  }

  return (
    <div
      className="relative min-h-screen"
      style={{
        background:
          'radial-gradient(circle at 50% 0%, rgba(148, 163, 184, 0.14), transparent 55%), var(--color-surface-page)',
      }}
    >
      <p className="absolute left-token-5 top-token-6 m-0 hidden font-mono text-token-meta tracking-[0.03em] text-text-faint sm:block">
        Licensed to: Acme Corp · 500 pipeline nodes
      </p>
      <div className="absolute right-token-5 top-token-6 flex items-center gap-token-2">
        <span className="h-[5px] w-[5px] rounded-full bg-success" aria-hidden="true" />
        <span className="font-mono text-token-meta tracking-[0.07em] text-text-muted">PRODUCTION</span>
      </div>

      <main className="flex min-h-screen items-center justify-center px-token-5 py-9">
        <div className="w-[400px] max-w-full overflow-hidden rounded-sm border border-border bg-surface-card">
          <div className="h-[3px] bg-primary" />
          <div className="px-token-7 pt-token-8">
            <div className="flex items-center gap-3.5">
              <span className="h-7 w-9 shrink-0">
                <img src={meridianLogomark} alt="" className="block h-full w-full" />
              </span>
              <div>
                <p className="m-0 text-token-xl font-semibold tracking-[-0.02em] text-text-primary">ConnectIQ</p>
                <p className="mt-token-2 font-mono text-token-xs font-medium uppercase tracking-[0.05em] text-text-muted">
                  Enterprise Data Integration
                </p>
              </div>
            </div>

            <div className="mt-token-6 border-t border-border" />

            <h1 className="mt-token-7 text-token-lg font-semibold tracking-[-0.02em] text-text-primary">
              Two-factor authentication
            </h1>
            <p className="mt-token-2 text-token-base text-text-secondary">
              Enter the 6-digit verification code generated by your authenticator app.
            </p>

            <div className="mt-token-6 inline-flex items-center gap-token-2 rounded-md border border-border bg-surface-page px-token-3 py-token-2">
              <span className="h-1.5 w-1.5 shrink-0 rounded-full bg-primary opacity-70" aria-hidden="true" />
              <img src={shieldCheckIcon} alt="" className="block h-[13px] w-[13px]" />
              <span className="text-token-sm font-medium tracking-[-0.01em] text-text-secondary-strong">
                Authenticator app
              </span>
            </div>

            <form className="mt-token-6 flex flex-col gap-token-5" onSubmit={handleSubmit} noValidate>
              {verifyError && (
                <p
                  id="tfa-verify-error"
                  ref={errorBannerRef}
                  tabIndex={-1}
                  className="m-0 rounded-md border border-danger-border bg-danger-bg p-token-4 text-token-base text-danger-strong focus-visible:outline-none"
                  role="alert"
                >
                  {verifyError}
                </p>
              )}

              <div className="flex flex-col gap-token-2">
                <span id="tfa-code-label" className="text-token-sm font-medium tracking-[-0.01em] text-text-primary">
                  Verification code
                </span>
                <div
                  className="flex items-center gap-token-3"
                  onPaste={handlePaste}
                  role="group"
                  aria-labelledby="tfa-code-label"
                >
                  <div className="flex flex-1 gap-token-2">
                    {digits.slice(0, 3).map((digit, i) => (
                      <OtpCell
                        key={i}
                        id={`tfa-code-${i}`}
                        position={i + 1}
                        value={digit}
                        onChange={(v) => setDigit(i, v)}
                        onKeyDown={(e) => handleKeyDown(i, e)}
                        inputRef={(el) => (inputRefs.current[i] = el)}
                        disabled={submitting}
                        error={Boolean(verifyError)}
                      />
                    ))}
                  </div>
                  <span className="text-token-base text-decorative-faint" aria-hidden="true">
                    –
                  </span>
                  <div className="flex flex-1 gap-token-2">
                    {digits.slice(3, 6).map((digit, i) => (
                      <OtpCell
                        key={i + 3}
                        id={`tfa-code-${i + 3}`}
                        position={i + 4}
                        value={digit}
                        onChange={(v) => setDigit(i + 3, v)}
                        onKeyDown={(e) => handleKeyDown(i + 3, e)}
                        inputRef={(el) => (inputRefs.current[i + 3] = el)}
                        disabled={submitting}
                        error={Boolean(verifyError)}
                      />
                    ))}
                  </div>
                </div>
                <p className="m-0 text-token-sm text-text-faint">
                  Codes refresh every 30 seconds. Use the current code shown in your app.
                </p>
              </div>

              <div className="flex items-center justify-between">
                <span className="text-token-sm text-text-faint">Didn&rsquo;t receive a code?</span>
                <button
                  type="button"
                  className="font-mono text-token-meta tracking-[0.01em] text-text-faint disabled:cursor-not-allowed enabled:text-primary enabled:hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
                  onClick={resend}
                  disabled={resending || cooldown > 0}
                  aria-live="polite"
                >
                  {resending ? 'Sending…' : cooldown > 0 ? `Resend available in ${cooldown}s` : 'Resend code'}
                </button>
              </div>
              {resendError && (
                <p className="m-0 text-token-sm text-danger" role="alert">
                  {resendError}
                </p>
              )}
              {resendSent && (
                <p className="m-0 text-token-sm text-success" role="status">
                  A new code has been sent.
                </p>
              )}

              <label className="flex items-center gap-3 text-token-base text-text-secondary-strong cursor-pointer">
                <input
                  type="checkbox"
                  className="h-[15px] w-[15px] rounded-sm accent-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
                  checked={trustDevice}
                  onChange={(e) => setTrustDevice(e.target.checked)}
                  disabled={submitting}
                />
                Trust this device for 30 days
              </label>

              <button
                type="submit"
                className="h-9 w-full rounded-md bg-primary text-token-base font-medium text-text-on-primary disabled:cursor-not-allowed disabled:opacity-60 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
                disabled={submitting || !codeComplete}
              >
                {submitting ? 'Verifying…' : 'Verify'}
              </button>
            </form>

            <div className="mt-token-6 flex flex-col items-center gap-token-3 pb-token-8">
              <button
                type="button"
                className="text-token-sm text-text-faint disabled:cursor-not-allowed"
                disabled
                title="Only the authenticator-app method is available — MOD-002 has not implemented an alternate 2FA delivery channel."
              >
                Use another method
              </button>
              <button
                type="button"
                className="flex items-center gap-1 text-token-sm text-text-secondary-strong hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
                onClick={() => navigate('/login')}
              >
                <img src={arrowLeftIcon} alt="" className="block h-[13px] w-[13px]" />
                Back to Sign In
              </button>
            </div>
          </div>

          <div className="flex items-center justify-between border-t border-border-subtle bg-surface-muted px-token-7 py-2.5">
            <span className="font-mono text-token-meta tracking-[0.03em] text-text-faint">Protected by ConnectIQ Enterprise Auth</span>
            <span className="font-mono text-token-meta tracking-[0.03em] text-text-faint">TLS 1.3 · v7.2.1</span>
          </div>
        </div>
      </main>

      <p className="absolute inset-x-0 bottom-token-6 m-0 text-center font-mono text-token-meta tracking-[0.02em] text-text-faint">
        © 2025 ConnectIQ Technologies, Inc. All rights reserved.
      </p>
    </div>
  );
}

function OtpCell({ id, position, value, onChange, onKeyDown, inputRef, disabled, error }) {
  return (
    <input
      id={id}
      ref={inputRef}
      type="text"
      inputMode="numeric"
      autoComplete="one-time-code"
      maxLength={1}
      className={`h-11 w-full rounded-md border bg-surface-card text-center text-[22px] text-text-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-primary disabled:cursor-not-allowed disabled:opacity-60 ${
        error ? 'border-danger' : 'border-border'
      }`}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      onKeyDown={onKeyDown}
      disabled={disabled}
      aria-label={`Verification code, digit ${position} of 6`}
      aria-invalid={error}
      aria-describedby={error ? 'tfa-verify-error' : undefined}
    />
  );
}
